### ISSUE TITLE
As a maintainer, I want the links for navigation to be in a json/yaml, so that I can easily reuse them in different components without having to hardcode the data

### ISSUE THREAD

**Issue by simon-wg** [cthit/chalmers.it#62]
### 📝 Description

I want to have a file containing all links and texts so that it can be reused in multiple components.
One example would be something like:
```yaml
Navigation:
  Sektionen:
    Link:
      URL: "/groups"
      Text: "Kommittéer, föreningar och andra instanser"
    Link:
      URL: "https://dokument.chalmers.it"
      Text: "Dokument"
  Link:
    URL: "/contact"
    Text: "Kontakt"

```

### ✅ Acceptance Criteria

-[] All navmenus use data from a file instead of hardcoded values.
-[] We have a file containing mappings of links, and dropdowns containing links.
